### ISSUE TITLE
Improve UI of the FilterPanel (1)

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/NEST-roadmap#63] opened 2022-07-28 10:30 UTC
Context: Current filter panel can become quite lengthy is not easy to navigate for app users, especially when the app contains 10+ dataset, locating a new variable to filter can involve a lot of scrolling back and forth.

- [x] https://github.com/insightsengineering/teal.slice/issues/70
- [x] ~~https://github.com/insightsengineering/teal.slice/issues/84~~
- [ ] ~~https://github.com/insightsengineering/teal.slice/issues/13~~
- [ ] ~~https://github.com/insightsengineering/teal.slice/issues/14~~
- [ ] ~~https://github.com/insightsengineering/teal.slice/issues/6~~
- [x] https://github.com/insightsengineering/teal.slice/issues/41

**Comment by nikolas-burkoff** [comment] 2022-08-03 12:06
Duplicate of #46  ?

**Comment by kumamiao** [comment] 2022-08-11 04:06
consolidated to separate the 2 issues (this one and #46) for 2 increments

**Closed as completed** 2022-10-04 20:18 UTC
Labels: teal, core
